
<div id="table-session">
	<?=$this->partial('uthando-session-manager/session-manager/list', [
		'models' => $this->models,
    ]);?>
</div>

<?php $this->inlineScript()->captureStart(); ?>
$(document).ready(function(){
	$('#table-session').dataGrid({
    	url : 'session/list',
    	query: { sort : 'id' },
    	paging : 'links',
    	columnSort: true
	});
});
<?php $this->inlineScript()->captureEnd(); ?>