
<?php $this->headTitle('Sessions') ?>
<?php $this->layout()->pageTitle = $this->translate('Sessions'); ?>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-list"></i> <?= $this->translate('Session List'); ?></h3>
    </div>
    <div class="panel-body">
        <?= $this->partial('uthando-admin/partial/search', [
            'name' => 'session',
            'searchInputs' => [
                $this->translate('Session Id') => 'id',
            ],
        ]); ?>
    </div>
    <div id="table-session" class="admin-table">
        <?= $this->partial('uthando-session-manager/session-manager/list', [
            'models' => $this->models,
        ]); ?>
    </div>
</div>

<?php $this->inlineScript()->captureStart(); ?>
$(document).ready(function(){
    $('#table-session').dataGrid({
        url : 'session/list',
        query: { sort : 'id' },
        paging : 'links',
        searchForm : $('#search-session'),
        columnSort: true
    });
});
<?php $this->inlineScript()->captureEnd(); ?>