    	
<div id="table-session" class="table-wrap">
	<?=$this->partial('uthando-session-manager/session-manager/list', array(
		'models' => $this->models
    ));?>
</div>

<?php $this->headScript()->captureStart(); ?>
$(document).ready(function(){
	$('#table-session').dataGrid({
    	url : 'session/list',
    	query: { sort : 'id' },
    	paging : 'links',
    	columnSort: true
	});
});
<?php $this->headScript()->captureEnd(); ?>