<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'UthandoSessionManager\Module'                                            => __DIR__ . '/Module.php',
    'UthandoSessionManager\Controller\Plugin\SessionContainer'                => __DIR__ . '/src/UthandoSessionManager/Controller/Plugin/SessionContainer.php',
    'UthandoSessionManager\Controller\SessionManagerController'               => __DIR__ . '/src/UthandoSessionManager/Controller/SessionManagerController.php',
    'UthandoSessionManager\Event\RouteListener'                               => __DIR__ . '/src/UthandoSessionManager/Event/RouteListener.php',
    'UthandoSessionManager\Hydrator\Session'                                  => __DIR__ . '/src/UthandoSessionManager/Hydrator/Session.php',
    'UthandoSessionManager\Mapper\Session'                                    => __DIR__ . '/src/UthandoSessionManager/Mapper/Session.php',
    'UthandoSessionManager\Model\Session'                                     => __DIR__ . '/src/UthandoSessionManager/Model/Session.php',
    'UthandoSessionManager\Service\Factory\SessionManagerFactory'             => __DIR__ . '/src/UthandoSessionManager/Service/Factory/SessionManagerFactory.php',
    'UthandoSessionManager\Service\Factory\SessionSaveHandlerFactory'         => __DIR__ . '/src/UthandoSessionManager/Service/Factory/SessionSaveHandlerFactory.php',
    'UthandoSessionManager\Service\SessionManager'                            => __DIR__ . '/src/UthandoSessionManager/Service/SessionManager.php',
    'UthandoSessionManager\Session\SaveHandler\DbTableGateway'                => __DIR__ . '/src/UthandoSessionManager/Session/SaveHandler/DbTableGateway.php',
    'UthandoSessionManager\SessionContainerTrait'                             => __DIR__ . '/src/UthandoSessionManager/SessionContainerTrait.php',
    'UthandoSessionManager\SessionManagerException'                           => __DIR__ . '/src/UthandoSessionManager/SessionManagerException.php',
    'UthandoSessionManager\View\DecodeSession'                                => __DIR__ . '/src/UthandoSessionManager/View/DecodeSession.php',
);
