<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'UthandoSessionManager\Module'                                            => __DIR__ . '/Module.php',
    'UthandoSessionManager\Controller\Plugin\SessionContainer'                => __DIR__ . '/src/UthandoSessionManager/Controller/Plugin/SessionContainer.php',
    'UthandoSessionManager\Controller\SessionManagerController'               => __DIR__ . '/src/UthandoSessionManager/Controller/SessionManagerController.php',
    'UthandoSessionManager\Event\RouteListener'                               => __DIR__ . '/src/UthandoSessionManager/Event/RouteListener.php',
    'UthandoSessionManager\Hydrator\Session'                                  => __DIR__ . '/src/UthandoSessionManager/Hydrator/Session.php',
    'UthandoSessionManager\Mapper\Session'                                    => __DIR__ . '/src/UthandoSessionManager/Mapper/Session.php',
    'UthandoSessionManager\Model\Session'                                     => __DIR__ . '/src/UthandoSessionManager/Model/Session.php',
    'UthandoSessionManager\Service\Factory\SessionManagerFactory'             => __DIR__ . '/src/UthandoSessionManager/Service/Factory/SessionManagerFactory.php',
    'UthandoSessionManager\Service\Factory\SessionSaveHandlerFactory'         => __DIR__ . '/src/UthandoSessionManager/Service/Factory/SessionSaveHandlerFactory.php',
    'UthandoSessionManager\Service\SessionManager'                            => __DIR__ . '/src/UthandoSessionManager/Service/SessionManager.php',
    'UthandoSessionManager\SessionContainerTrait'                             => __DIR__ . '/src/UthandoSessionManager/SessionContainerTrait.php',
    'UthandoSessionManager\SessionManagerException'                           => __DIR__ . '/src/UthandoSessionManager/SessionManagerException.php',
    'UthandoSessionManager\View\DecodeSession'                                => __DIR__ . '/src/UthandoSessionManager/View/DecodeSession.php',
    'UthandoSessionManagerTest\Bootstrap'                                     => __DIR__ . '/test/Bootstrap.php',
    'UthandoSessionManagerTest\Framework\TestCase'                            => __DIR__ . '/test/UthandoSessionManagerTest/Framework/TestCase.php',
    'UthandoSessionManagerTest\Hydrator\SessionTest'                          => __DIR__ . '/test/UthandoSessionManagerTest/Hydrator/SessionTest.php',
    'UthandoSessionManagerTest\Model\SessionTest'                             => __DIR__ . '/test/UthandoSessionManagerTest/Model/SessionTest.php',
    'UthandoSessionManagerTest\Service\Factory\SessionManagerFactoryTest'     => __DIR__ . '/test/UthandoSessionManagerTest/Service/Factory/SessionManagerFactoryTest.php',
    'UthandoSessionManagerTest\Service\Factory\SessionMangerCustomConfigTest' => __DIR__ . '/test/UthandoSessionManagerTest/Service/Factory/SessionSaveHandlerFactoryTest.php',
    'UthandoSessionManagerTest\Service\SessionManagerTest'                    => __DIR__ . '/test/UthandoSessionManagerTest/Service/SessionManagerTest.php',
);
